#!/bin/bash

CONFIG_FILE=$HOME/.config/ms-mail-automation/config.json
if [ ! -f $CONFIG_FILE ]; then
	echo "config.json not found"
	exit 1
fi

SCRIPT_DIR=$(dirname "$0")
CONFIG_DIR=
PYENV=$SCRIPT_DIR/.venv

source $PYENV/bin/activate || exit 1

python $SCRIPT_DIR/main.py $CONFIG_FILE
